### PR TITLE
Update cost constants

### PR DESCRIPTION
**Pull request by reedrosenbluth**
Update the cost constants based on latest benchmarking data

### CODE REVIEW

**Review by kantai — APPROVED** [review]
LGTM! Thanks Reed

**Comment by diwakergupta** [comment]
Is this the final _final_ pass on costs? I noticed that https://github.com/blockstack/clarity-benchmarking/issues/27 is closed but some functions still have very close but different costs (e.g. pow vs. sqrti)

Besides that, LGTM.

**Comment by kantai** [comment]
Yes -- I'll go through and smooth these costs out now.

**Review by diwakergupta — APPROVED** [review]
LGTM!

**Pull request merged**
